@startuml

namespace Common {
    class User extends BaseModel {
        +id : int
        +name : String
        @Validate(String::class, notNull = true)
        +email : String
    }

    abstract class BaseModel<T> implements Orm.IBaseModel {
        ---
        +validate() : Set<ConstraintViolation>
        +populateAttributes(attributes : Map<String, ColumnValue>)
        +getAttributes() : Map<String, ColumnValue>
    }
}

namespace Orm {

    interface IBaseModel<T> extends Serializable {
        ---
        +validate() : Set<ConstraintViolation>
        +populateAttributes(attributes : Map<String, ColumnValue>)
        +getAttributes() : Map<String, ColumnValue>
        +compareTo(model : IBaseModel)
    }


    abstract class BaseRecord<T> implements Pagination {
        #state : BaseModel<T>
        -dbState : BaseModel<T>
        -deleteFunctionality : DeleteFunctionality
        ---
        #getDeleteFunctionality() : DeleteFunctionality
        -isDirty() : boolean
        -exists() : boolean
        -- State manipulators --
        +setAttribute(name : String, value : V | ColumnValue)
        +getAttribute(name : String) : ColumnValue
        -- Database operations --
        +create(attributes : Map | BaseModel<T>) : BaseRecord<T>
        +save() : boolean
        +update(attributes : Map | BaseModel<T>) : boolean
        +all() : List<User>
        +fill(attributes : Map | BaseModel<T>) : User
        +delete() : boolean
        -- Relations --
        +hasOne(class : Class<Model>, foreignKey : String, localKey : String)
        +belongsTo(class : class<Model>, foreignKey : String, localKey : String)
        +hasMany(class : class<Model>, foreignKey : String, localKey : String)
        +hasManyThrough(class : class<Model>, foreignKey : String, localKey : String)
    }


    interface Pagination {
        ---
        +paginate()
    }

    interface DeleteFunctionality {
        +delete() : boolean
    }

    BaseRecord "1" o-- "1" DeleteFunctionality

    class DefaultDeleteFunctionality implements DeleteFunctionality {
        +delete() : boolean
    }

    class SoftDelete implements DeleteFunctionality {
        #deleted_at : String
        ---
        +restore() : BaseRecord
        +delete() : boolean
        +delete(force : boolean) : boolean
    }

    interface ISoftDelete {
        #getDeleteFunctionality() : DeleteFunctionality
        +restore() : BaseRecord - Default
        +forceDelete(force : boolean) : boolean - Default
    }

    class SelectQuery<T extends BaseRecord<V>, V extends IBaseModel<V>> {
        -model : T
        -table : String
        -selects : Set<String>
        -wheres : LinkedList<ConditionalStatement>
        -groupBy : LinkedHashSet<String>
        -orderBy : LinkedHashSet<String>
        -having : LinkedList<ConditionalStatement>
        ---
        +select(columns : String...)
        +where(key : String, operator : SqlOperator, value : T, useAnd : boolean = true)
        +whereNot(column : String, value : V)
        +whereEquals(column : String, value : V)
        +whereIsNull(column : String)
        +having(key : String, operator : SqlOperator, value : T, useAnd : boolean = true)
        +groupBy(column : String...)
        +orderBy(column : String...)
        +get() : List<T>
        +first() : T
        +delete() : boolean
        +getSqlStatement() : String
        +populateStatement(statement : PreparedStatement)
    }

    SelectQuery "1" o-- "*" ConditionalStatement

    class UpdateQuery {
        -table : String
        -sets : LinkedList<ConditionalStatement>
        -wheres : LinkedList<ConditionalStatement>
        ---
        +set(column : String, value : V)
        +where(key : String, operator : SqlOperator, value : T, useAnd : boolean = true)
        +whereNot(column : String, value : V)
        +whereEquals(column : String, value : V)
        +whereIsNull(column : String)
        +populateStatement(statement : PreparedStatement)
        +getSqlStatement() : String
    }

    UpdateQuery "1" o-- "*" ConditionalStatement

    class InsertQuery<T> {
        -model : T
        -table : String
        ---
        +set(column : String, value : V)
        +where(key : String, operator : SqlOperator, value : T, useAnd : boolean = true)
        +whereNot(column : String, value : V)
        +whereEquals(column : String, value : V)
        +whereIsNull(column : String)
        +populateStatement(statement : PreparedStatement)
        +getSqlStatement() : String
    }

    class DeleteQuery<T> {
        -table : String
        -wheres : LinkedList<ConditionalStatement>
        ---
        +populateStatement(statement : PreparedStatement)
        +getSqlStatement() : String
    }

    DeleteQuery "1" o-- "*" ConditionalStatement

    class ConditionalStatement<T> {
        key : String
        operator : SqlOperator
        value : T
        useAnd : boolean = true
        ---
        getStatement() : String
    }

    ConditionalStatement "1" o-- "1" SqlOperator

    enum SqlOperator {

    }


}

namespace Server {
    class UserModel extends Orm.BaseRecord implements Orm.ISoftDelete {
        #state : Common.User
        -deleteFunctionality = new SoftDelete()
    }

    UserModel "1" o--- "1" Common.User
}

@enduml